### ISSUE TITLE
Crash when running container

### ISSUE THREAD

**Issue by rfaircloth-splunk** [splunk/splunk-connect-for-snmp-traps#25]
`Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pysnmp/smi/builder.py", line 401, in loadModules
    self.loadModule(modName, **userCtx)
  File "/usr/local/lib/python3.8/site-packages/pysnmp/smi/builder.py", line 377, in loadModule
    raise error.MibNotFoundError(
pysnmp.smi.error.MibNotFoundError: MIB file "NET-SNMP-EXAMPLES-MIB.py[co]" not found in search path (DirMibSource('/usr/local/lib/python3.8/site-packages/pysnmp/smi/mibs'), DirMibSource('/usr/local/lib/python3.8/site-packages/pysnmp/smi/mibs/instances'), DirMibSource('pysnmp_mibs'), DirMibSource('/root/.pysnmp/mibs'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/bin/sc4snmp-traps", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/splunk_connect_for_snmp_traps/snmp_trap_server.py", line 37, in main
    trap_server = TrapServer(server_config)
  File "/usr/local/lib/python3.8/site-packages/splunk_connect_for_snmp_traps/manager/trap_server.py", line 24, in __init__
    self._translator = Translator(server_config)
  File "/usr/local/lib/python3.8/site-packages/splunk_connect_for_snmp_traps/manager/translator.py", line 15, in __init__
    self._mib_view_controller = self.build_mib_compiler(self._load_list)
  File "/usr/local/lib/python3.8/site-packages/splunk_connect_for_snmp_traps/manager/translator.py", line 25, in build_mib_compiler
    mibBuilder.loadModules(module)
  File "/usr/local/lib/python3.8/site-packages/pysnmp/smi/builder.py", line 410, in loadModules
    raise error.MibNotFoundError('%s compilation error(s): %s' % (modName, errs))
pysnmp.smi.error.MibNotFoundError: NET-SNMP-EXAMPLES-MIB compilation error(s): missingcaused by <class 'pysnmp.smi.error.MibNotFoundError'>: MIB file "NET-SNMP-EXAMPLES-MIB.py[co]" not found in search path (DirMibSource('/usr/local/lib/python3.8/site-packages/pysnmp/smi/mibs'), DirMibSource('/usr/local/lib/python3.8/site-packages/pysnmp/smi/mibs/instances'), DirMibSource('pysnmp_mibs'), DirMibSource('/root/.pysnmp/mibs'))`

**Comment by rfaircloth-splunk** [comment]
Confirmed this issue is caused by the default config requiring loading missing mibs we do need a try catch to handle this
